---
- name: Create Roles
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'role.yml.j2', template_vars=dict(role=item)) }}"
  loop: "{{ k8s_roles }}"

- name: Create ClusterRoles
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'clusterrole.yml.j2', template_vars=dict(role=item)) }}"
  loop: "{{ k8s_clusterroles }}"

- name: Create RoleBindings
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'rolebinding.yml.j2', template_vars=dict(binding=item)) }}"
  loop: "{{ k8s_rolebindings }}"

- name: Create ClusterRoleBindings
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'clusterrolebinding.yml.j2', template_vars=dict(binding=item)) }}"
  loop: "{{ k8s_clusterrolebindings }}"

- name: Determine and delete obsolete RoleBindings
  block:
    - name: Get current RoleBindings
      set_fact:
        current_rolebindings: "{{ lookup('community.kubernetes.k8s', kind='RoleBinding', label_selector='kubernetes.io/managed-by=ansible-role-kubernetes-rbac', wantlist=True) }}"
    - include: delete_rolebinding.yml
      loop: "{{ current_rolebindings }}"
  when: cleanup_rolebindings

- name: Determine and delete obsolete ClusterRoleBindings
  block:
    - name: Get current ClusterRoleBindings
      set_fact:
        current_clusterrolebindings: "{{ lookup('community.kubernetes.k8s', kind='ClusterRoleBinding', label_selector='kubernetes.io/managed-by=ansible-role-kubernetes-rbac', wantlist=True) }}"
    - include: delete_clusterrolebinding.yml
      loop: "{{ current_clusterrolebindings }}"
  when: cleanup_clusterrolebindings

- name: Determine and delete obsolete Roles
  block:
    - name: Get current Roles
      set_fact:
        current_roles: "{{ lookup('community.kubernetes.k8s', kind='Role', label_selector='kubernetes.io/managed-by=ansible-role-kubernetes-rbac', wantlist=True) }}"
    - include: delete_role.yml
      loop: "{{ current_roles }}"
  when: cleanup_roles

- name: Determine and delete obsolete ClusterRoles
  block:
    - name: Get current ClusterRoles
      set_fact:
        current_clusterroles: "{{ lookup('community.kubernetes.k8s', kind='ClusterRole', label_selector='kubernetes.io/managed-by=ansible-role-kubernetes-rbac', wantlist=True) }}"
    - include: delete_clusterrole.yml
      loop: "{{ current_clusterroles }}"
  when: cleanup_clusterroles
